# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: py_stag_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      id: step_one
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: Install dependencies
      id: step_two
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set password
      id: step_three
      run: |
          echo "TSTXBN_P=@5Giggles" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v -s -m rr_comp

